POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Testing blog creation with reference to user",
    "author": "Duane Gadama",
    "url": "example.com",
    "likes": "677"
}